version: '3'

services:
  # Serviço de aplicação (Node.js)
  app:
    image: node:14
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    working_dir: /app
    command: npm start

  # Serviço Prometheus
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  # Monta o arquivo de configuração
    ports:
      - "9090:9090"  # Porta padrão do Prometheus

  # Serviço Grafana
  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"  # Grafana usa a porta 3000 internamente
    depends_on:
      - prometheus
    volumes:
      - grafana-storage:/var/lib/grafana  # Armazenamento persistente para Grafana

volumes:
  grafana-storage:

